"""add game_name and game_image to favorites

Revision ID: 3520b07950a3
Revises: b3313b21113a
Create Date: 2026-01-13 00:29:59.889636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3520b07950a3'
down_revision = 'b3313b21113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('game_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('game_image')
        batch_op.drop_column('game_name')

    # ### end Alembic commands ###
