"""remove foreign key from favorites

Revision ID: ff88c64aa71e
Revises: 884443bf9c7f
Create Date: 2026-01-13 23:24:16.588981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff88c64aa71e'
down_revision = '884443bf9c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_game_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_foreign_key('favorites_game_id_fkey', 'games', ['game_id'], ['game_id'])

    # ### end Alembic commands ###
